config/routes.rb
Rails.application.routes.draw do

  #root
  root to:'home#index' 

  #
  # Api 1.0  
  #
  namespace :api1 do
    # Rotas de usuario
    post '/users/login', to: 'users#login'      
    post '/users/new', to: 'users#new'    
    put '/users/edit', to: 'users#edit'    
    put '/users/edit-password', to: 'users#edit_password'    
    post '/users/recover', to: 'users#recover'
    get '/users/show', to: 'users#show'
    delete '/users/destroy', to: 'users#destroy' 
    # Rotas cartelas   
    get '/cards', to: 'cards#index'          
    get '/cards/list', to: 'cards#list'        
    get '/cards/ranking', to: 'cards#ranking'          
    get '/cards/full', to: 'cards#full'          
    post '/cards/buy', to: 'cards#buy'  
    # Rotas sortitions
    get '/sortitions/next', to: 'sortitions#next'   
    get '/sortitions/incurse', to: 'sortitions#incurse'   
    # Rotas results
    post '/results', to: 'results#index' 
    post '/results/all', to: 'results#all' 
    # Rotas parametros
    get '/params/show', to: 'params#show'    
  end

  #
  # Painel admin 
  #
  namespace :admin do
    # reports
    root to: 'reports#index'        
    post '/reports', to: 'reports#index'
    # regions
    resources :regions 
    # users
    resources :users, :except => [:show]  
    get '/users/login', to: 'users#set_login'             
    post '/users/login', to: 'users#login'        
    get '/users/logout', to: 'users#logout'
    # clients          
    resources :clients, :except => [:show]  
  end

end

app/models/region.rb
class Region < ApplicationRecord
end

app/controllers/admin/regions_controller.rb
class Admin::RegionsController < Admin::ApplicationController
  before_action :set_admin_region, only: [:show, :edit, :update, :destroy]

  # GET /admin/regions
  def index
    @admin_regions = Region.all
  end

  # GET /admin/regions/1
  def show
  end

  # GET /admin/regions/new
  def new
    @admin_region = Region.new
  end

  # GET /admin/regions/1/edit
  def edit
  end

  # POST /admin/regions
  def create
    @admin_region = Region.new(admin_region_params)

    if @admin_region.save
      redirect_to @admin_region, notice: 'Region was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /admin/regions/1
  def update
    if @admin_region.update(admin_region_params)
      redirect_to @admin_region, notice: 'Region was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /admin/regions/1
  def destroy
    @admin_region.destroy
    redirect_to admin_regions_url, notice: 'Region was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_region
      @admin_region = Region.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def admin_region_params
      params.require(:admin_region).permit(:name, :user_id)
    end
end

app/helpers/admin/regions_helper.rb
module Admin::RegionsHelper
end

app/views/admin/regions/_form.html.erb
<%= form_for([ :admin,  admin_region], html: 
		{ class: "form-horizontal", role: "form" }) do |form| %>

	<% if admin_region.errors.any? %>  
		<div id="error_explanation">
			<h2>
				<%= pluralize(admin_region.errors.count, "erro") %> 
				ao salvar  	
			</h2>
			<ul>
				<% admin_region.errors.full_messages.each do |message| %>
					<li><%= message %></li>
				<% end %>
			</ul>  
		</div>
	<% end %>

	<div class="field">
		<%= form.label :name %>
		<%= form.text_field :name, class: "form-control", :required => true %>
	</div>

	<div class="field">  
		<%= form.label :user_id %>
		<%= form.text_field :name, class: "form-control", :required => true %>
	</div>

	<div class="actions">
		<%= form.submit %>
	</div>

<% end %>

app/views/admin/regions/edit.html.erb
<h1>Editing Admin Region</h1>

<%= render 'form', admin_region: @admin_region %>

<%= link_to 'Show', @admin_region %> |
<%= link_to 'Back', admin_regions_path %>

app/views/admin/regions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Admin Regions</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admin_regions.each do |admin_region| %>
      <tr>
        <td><%= admin_region.name %></td>
        <td><%= admin_region.user_id %></td>
        <td><%= link_to 'Show', admin_region %></td>
        <td><%= link_to 'Edit', edit_admin_region_path(admin_region) %></td>
        <td><%= link_to 'Destroy', admin_region, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Admin Region', new_admin_region_path %>

app/views/admin/regions/new.html.erb
<h1>Cadastrar região</h1>

<%= render 'form', admin_region: @admin_region %>

<%= link_to 'Back', admin_regions_path %>

app/views/admin/regions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @admin_region.name %>
</p>

<p>
  <strong>User:</strong>
  <%= @admin_region.user_id %>
</p>

<%= link_to 'Edit', edit_admin_region_path(@admin_region) %> |
<%= link_to 'Back', admin_regions_path %>