config/routes.rb
Rails.application.routes.draw do

  #root
  root to:'home#index' 

  #
  # Api 1.0  
  #
  namespace :api1 do
    # Rotas de usuario
    post '/users/login', to: 'users#login'      
    post '/users/new', to: 'users#new'    
    put '/users/edit', to: 'users#edit'    
    put '/users/edit-password', to: 'users#edit_password'    
    post '/users/recover', to: 'users#recover'
    get '/users/show', to: 'users#show'
    delete '/users/destroy', to: 'users#destroy' 
    # Rotas cartelas   
    get '/cards', to: 'cards#index'          
    get '/cards/list', to: 'cards#list'        
    get '/cards/ranking', to: 'cards#ranking'          
    get '/cards/full', to: 'cards#full'          
    post '/cards/buy', to: 'cards#buy'  
    # Rotas sortitions
    get '/sortitions/next', to: 'sortitions#next'   
    get '/sortitions/incurse', to: 'sortitions#incurse'   
    # Rotas results
    post '/results', to: 'results#index' 
    post '/results/all', to: 'results#all' 
    # Rotas parametros
    get '/params/show', to: 'params#show'    
  end

  #
  # Painel admin 
  #
  namespace :admin do
    # reports
    root to: 'reports#index'        
    post '/reports', to: 'reports#index'
    # regions
    resources :regions 
    # users
    resources :users, :except => [:show]  
    get '/users/login', to: 'users#set_login'             
    post '/users/login', to: 'users#login'        
    get '/users/logout', to: 'users#logout'
    # clients          
    resources :clients, :except => [:show]  
  end

end

app/models/user.rb
class User < ApplicationRecord

    validates_length_of :name, minimum: 5, maximum: 255 
    validates :email, presence: true
    validates :email, uniqueness: true, :on => :create
    validates :phone, presence: true

    has_secure_password

  def as_json(options={})
    {
      :id => id,
      :name => name,
      :email => email,
      :credit => credit,
      :phone => phone 
    }
  end

    
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::ApplicationController

  before_action :authorize_request, except: [:login, :set_login]  
  before_action :set_admin_user, only: [:show, :edit, :update, :destroy]


  def set_login
    render :login, layout: "admin_login"
  end


  def login
    user = User
      .where("email"  => params[:email])      
      .where("status" => 1)     
      .where("level" => 1)     
      .first 
    @data = Hash.new
    if user&.authenticate(params[:password])    
      ap user
      session[:current_user_token] = JsonWebToken.encode(user_id: user.id) 
      redirect_to '/admin/users'
    else
      render :login, layout: "admin_login"   
    end  
  end


  def logout
    session[:current_user_token] = nil  
    redirect_to controller: "users", action: "login"    
  end


  def index
    @admin_users = User.where("level" => 1)
  end 


  def show
  end


  def new
    @admin_user = User.new
  end


  def edit
  end


  def create
    @admin_user = User.new(admin_user_params)

    if @admin_user.save
      redirect_to @admin_user, notice: 'User was successfully created.'
    else
      render :new
    end
  end


  def update
    if @admin_user.update(admin_user_params)
      redirect_to @admin_user, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end


  def destroy
    @admin_user.destroy
    redirect_to admin_users_url, notice: 'User was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_user
      @admin_user = User.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def admin_user_params
      params.require(:admin_user).permit(:level, :name, :email, :password, :credit, :credit, :phone)
    end
end

app/controllers/api1/users_controller.rb
class Api1::UsersController < ApplicationController


  before_action :authorize_request, except: [:login, :new]


  # 
  # THIS METHOD SET LOGIN 
  #   
  def login
    user = User
      .where("email"  => params[:user])      
      .where("status" => 1)     
      .where("level" => 2)     
      .first 
    @data = Hash.new
    if user&.authenticate(params[:password])
      # user = user.attributes.except('password_digest')   
      @data[:token]           = JsonWebToken.encode(user_id: user.id)
      @data[:time]            = Time.now + 24.hours.to_i
      @data[:login_status]    = 1
      @data[:login_message]   = "Logado com sucesso!!!"    
      @data[:user] = user
    else
      @data[:login_status]    = 0  
      @data[:login_message]   = "Usuário ou senha inválidos..."  
      @data[:user] = nil
    end   
  end


  # 
  # THIS METHOD UPDATE USER 
  #   
  def edit
    @user = User
      .where("id"  => @current_user.id)      
      .first 
    @user.name     = params[:name]    
    @user.email    = params[:email]    
    @user.phone    = params[:phone]     
    @data = Hash.new 
    if @user.save
       @data[:user_save_status] = 1
       @data[:user] = @user
    else
       @data[:user] = @user
       @data[:user_save_status] = 0
       @data[:errors] = @user.errors
    end   
  end


  # 
  # THIS METHOD UPDATE PASSWORD 
  #   
  def edit_password
    @user = User
      .where("id"  => @current_user.id)      
      .first 
    @user.password = params[:password]    
    @data = Hash.new 
    if @user.save
       @data[:user_save_status] = 1  
       @data[:user] = @user
    else
       @data[:user] = @user
       @data[:user_save_status] = 0
       @data[:errors] = @user.errors
    end       
  end


  # 
  # THIS METHOD SET NEW A USER
  # 
  def new
    @user = User.new
    @user.name     = params[:name]    
    @user.email    = params[:email]    
    @user.phone    = params[:phone]    
    @user.password = params[:password]  
    @data = Hash.new 
    if @user.save
       @data[:user_save_status] = 1
       @data[:user] = @user
    else
       @data[:user] = nil
       @data[:user_save_status] = 0
       @data[:errors] = @user.errors
    end  
  end


  # 
  # THIS METHOD GET LOGGED USER  
  # 
  def show
    @data = Hash.new  
    @data[:user] = @current_user
  end


  # 
  # This method set new a user 
  # 
  def load
    @users = User.all
    render json: @users, status: :ok    
  end


  # 
  # THIS METHOD DISABLE A USER 
  # 
  def destroy
    user = User.find_by id: @current_user.id   
    @data = Hash.new
    @data[:user_delete_status] = 0   
    if user
      user.status = 0  
      if user.save  
        @data[:user_delete_status] = 1    
      end
    end    
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/_form.html.erb
<%= form_with(model: admin_user, local: true) do |form| %>
  <% if admin_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(admin_user.errors.count, "error") %> prohibited this admin_user from being saved:</h2>

      <ul>
        <% admin_user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :level %>
    <%= form.number_field :level %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password %>
  </div>

  <div class="field">
    <%= form.label :credit %>
    <%= form.text_field :credit %>
  </div>

  <div class="field">
    <%= form.label :credit %>
    <%= form.text_field :credit %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/users/edit.html.erb
<h1>Editing Admin User</h1>

<%= render 'form', admin_user: @admin_user %>

<%= link_to 'Show', @admin_user %> |
<%= link_to 'Back', admin_users_path %>

app/views/admin/users/index.html.erb
<h1>
  Operadores cadastrados
</h1>

<table class="table" >
  <thead>
    <tr>
      <th>Código</th>
      <th>Nome</th>
      <th>Email</th>
      <th>Telefone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admin_users.each do |admin_user| %>
      <tr>
        <td><%= admin_user.id %></td>
        <td><%= admin_user.name %></td>
        <td><%= admin_user.email %></td>
        <td><%= admin_user.phone %></td>

        <td class="text-center" >
            <%= link_to ( admin_user_path(admin_user) ) do %>
              <label class="btn btn-primary" >
                <i class="fas fa-eye" ></i>
              </label>
            <% end %>
            <%= link_to ( edit_admin_user_path(admin_user) ) do %>
              <label class="btn btn-primary" >
                <i class="fas fa-edit" ></i>
              </label>
            <% end %>
            <%= link_to ( "/admin/destroy/" + admin_user.id.to_s ) do %>
              <label class="btn btn-danger" onclick="return confirm('Tem certeza?');" >
                <i class="fas fa-trash-alt" ></i>
              </label>
            <% end %> 
        </td>


      </tr>
    <% end %>
  </tbody>
</table>

<br>

<a href="/users/admin/new" class="btn-lg btn btn-success float--button--right" >
  +
</a>

app/views/admin/users/login.html.erb
<div class="login--container" >
	<div class="sidenav">
		<div class="login-main-text">
			<div class="col-sm-4 offset-sm-4">
				<h2>Login</h2>
			</div>
		</div>
	</div>
	<div class="main">
		<div class="col-sm-4 offset-sm-4">
			<div class="login-form">
				<form method="POST" action="/admin/users/login" >  
					<div class="form-group">
						<label></label>
						<input
						required
						name="email"
						type="email"
						class="form-control"
						placeholder="Email">
					</div>
					<div class="form-group">
						<input
						name="password"
						type="password"
						required
						class="form-control"
						placeholder="Senha">
					</div>
					<button type="submit" class="btn btn-default">
						Entrar
					</button>
				</form>
			</div>
		</div>
	</div>
</div>

app/views/admin/users/new.html.erb
<h1>New Admin User</h1>

<%= render 'form', admin_user: @admin_user %>

<%= link_to 'Back', admin_users_path %>

app/views/admin/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Level:</strong>
  <%= @admin_user.level %>
</p>

<p>
  <strong>Name:</strong>
  <%= @admin_user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @admin_user.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @admin_user.password %>
</p>

<p>
  <strong>Credit:</strong>
  <%= @admin_user.credit %>
</p>

<p>
  <strong>Credit:</strong>
  <%= @admin_user.credit %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @admin_user.phone %>
</p>

<%= link_to 'Edit', edit_admin_user_path(@admin_user) %> |
<%= link_to 'Back', admin_users_path %>